#!/usr/bin/env bash
s1=$#
if (( $# == 0 ))then
	echo give an argument
        exit 1
fi

# using for loop for checking all the given arguments
for name in "$@"; do
      case "$name" in  
	parv)  echo "ohh hii parv";;
	nevil) echo "ohh hi nevil";;
	ayush) echo "ohh hi ayush";;
	*)     echo "your access is $name";;
esac
done
echo "total arguments given is: $s1"
